export const STORINGBUYERINFO = "STORINGBUYERINFO";
export const STORINGSELLERINFO = "STORINGSELLERINFO";
export const STORINGCONSIGNMENTINFO = "STORINGCONSIGNMENTINFO";
export const DETAILSERROR = "DETAILSERROR";
export const DETAILSLOADING = "DETAILSLOADING";
