export const STORINGYARNDATAFROMSERVER = "STORINGYARNDATAFROMSERVER";
export const OPENCLOSEMODALINHISTORY = "OPENCLOSEMODALINHISTORY";

export const CONSIGNMENTLOADING = "CONSIGNMENTLOADING";
export const CONSIGNMENTERROR = "CONSIGNMENTERROR";
