export const INDIVIDUALYARNDELTELOADING = "INDIVIDUALYARNDELTELOADING";
export const INDIVIDUALYARNDELTEERROR = "INDIVIDUALYARNDELTEERROR";
export const INDIVIDUALYARNDELTEMODAL = "INDIVIDUALYARNDELETEMODAL";
export const INDIVIDUALYARNDELETEIDENTIFIER = "INDIVIDUALYARNDELETEIDENTIFIER";
