export const CUSTOMERVIEWLOADING = "CUSTOMERVIEWLOADING";
export const CUSTOMERVIEWERROR = "CUSTOMERVIEWERROR";

export const BUYERLISTSTORE = "BUYERLISTSTORE";
export const SELLERLISTSTORE = "SELLERLISTSTORE";
