// export const LOADING = "LOADING";
// export const ERROR = "ERROR";

// export const BUYERLISTSTORE = "BUYERLISTSTORE";
// export const SELLERLISTSTORE = "SELLERLISTSTORE";

// export const STORINGYARNDATAFROMSERVER = "STORINGYARNDATAFROMSERVER";
// export const OPENCLOSEMODALINHISTORY = "OPENCLOSEMODALINHISTORY";

// export const BUYERPDFRECIPT = "BUYERPDFRECIPT";

// export const AUTHSTART = "AUTHSTART";
// export const AUTHSUCCESS = "AUTHSUCCESS";
// export const AUTHFAIL = "AUTHFAIL";
// export const AUTHEXPIRY = "AUTHEXPIRY";
// export const AUTHLOGOUT = "AUTHLOGOUT";
