export const LOADING = "LOADING";
export const BUYERLISTSTORE = "BUYERLISTSTORE";
export const SELLERLISTSTORE = "SELLERLISTSTORE";
export const ERROR = "ERROR";

export const STORINGYARNDATAFROMSERVER = "STORINGYARNDATAFROMSERVER";
export const OPENCLOSEMODALINHISTORY = "OPENCLOSEMODALINHISTORY";
